### PR TITLE
chore(ion): fix comments in text

### PR DESCRIPTION
**Pull request by BenjaminMoe**
In our previous Pull Request we managed to get a Create and Resolve operation working. We want to continue in this pull request to get the other Operations working in the test. If we can figure out how to do them. The Ion CLI was nice enough to generate a create request body for us, but doesn't seem to include any of the other operations, maybe we can dig through the spec and figure out what needs to be done. 

https://identity.foundation/sidetree/api/#update
```
{
    "type": "update",
    "didSuffix": SUFFIX_STRING,
    "revealValue": REVEAL_VALUE,
    "delta": DELTA_OBJECT,
    "signedData": JWS_SIGNED_VALUE
}
```

This is what we need to send to the server.  The did suffix should be `EiBgMkQDrUjGYkUZqQgTiOkZeyQiQgNuYZLiW1S9M-oDCA`. Those two are easy, but we need to figure out what to do with the `revealValue`, `delta` and `signedData`.

### CODE REVIEW

**Comment by BenjaminMoe** [comment]
Going down the list, first we have the `revealValue`. We can take a look at the spec here: https://identity.foundation/sidetree/spec/#file-structures

Screenshot_2021-12-03 DIF Sidetree Protocol(1)

It's a hash of the commitment value? That's not very descriptive, but I'm guessing the "commitment value" is effectively the delta object in this case?

Screenshot_2021-12-03 DIF Sidetree Protocol(2)

Next step is what do we need to include for the delta?

**Comment by BenjaminMoe** [comment]
I guess that means we first need to figure out the delta object then?

Screenshot_2021-12-03 DIF Sidetree REST API

The link for `Update Operation Delta Object` doesn't actually go anywhere. I feel like I've [seen this somewhere before](https://www.youtube.com/watch?v=jluv2HxFEqs). Since the documentation doesn't provide any help here, and no one bothered to implement update in the CLI, we have a few options available to us.

[x] 1. Throw our computer out the window. 
[ ] 2. Throw random requests at the API hoping god shows us mercy
[ ] 3. Look for examples in the Sidetree repository
[ ] 4. Beg for help

**Comment by BenjaminMoe** [comment]
Documentation was a failure, but it looks the Sidetree repository has a test for us to reference. https://github.com/decentralized-identity/sidetree/blob/6a6ef478ada962de9171315e10b4dd2a8deaecfd/tests/generators/OperationGenerator.ts#L433

```
  public static async createUpdateOperationRequest (
    didSuffix: string,
    updatePublicKey: JwkEs256k,
    updatePrivateKey: JwkEs256k,
    nextUpdateCommitmentHash: string,
    patches: any,
    multihashAlgorithmCodeToUse?: number,
    multihashAlgorithmForRevealValue?: number
  ) {
    const revealValue = Multihash.canonicalizeThenHashThenEncode(updatePublicKey, multihashAlgorithmForRevealValue);

    const delta = {
      patches,
      updateCommitment: nextUpdateCommitmentHash
    };
    const deltaHash = Multihash.canonicalizeThenHashThenEncode(delta, multihashAlgorithmCodeToUse);

    const signedDataPayloadObject = {
      updateKey: updatePublicKey,
      deltaHash: deltaHash
    };
    const signedData = await OperationGenerator.signUsingEs256k(signedDataPayloadObject, updatePrivateKey);

    const updateOperationRequest = {
      type: OperationType.Update,
      didSuffix,
      revealValue,
      delta,
      signedData
    };

    return updateOperationRequest;
  }
```

We might tr console.logging the output from the test to be able to capture a set of operations and then test it against our local Ion install.

**Comment by BenjaminMoe** [comment]
In terms of hints to follow, the sidetree repository seems to have the most information. The problem is that it doesn't look like there is a set of fixtures to use, but there are tests. So we can try logging values from the test to see if it gives us what we need for the rest of the operations. 

```
--- 1. CREATE OPERATION REQUEST ---

curl --header "Content-Type: application/json" \
--request POST \
--data '{"type":"create","suffixData":{"deltaHash":"EiCrwEPnRbOrIAXifITZ9hTHfHTlwo_TkRKiYaYT5WibBQ","recoveryCommitment":"EiDVaPWhmSZ4Ytp5JfmTuKIHAYySw9ZS0dxG3vd9pxb3pw"},"delta":{"updateCommitment":"EiBJQqYrab1Fw_Mo6SCihrVBfF4s7wGqYLVkgQvJHgfyUg","patches":[{"action":"replace","document":{"publicKeys":[{"id":"signingKey","type":"EcdsaSecp256k1VerificationKey2019","publicKeyJwk":{"kty":"EC","crv":"secp256k1","x":"qCMZ35fujJut5x3V0C7Zwm6saxggPp91Wtf6iWyu0kY","y":"1MwzYwNR1RW5juCaNdhLbwhw8TTyGgJVgDhDWGBKico"},"purposes":["authentication","assertionMethod","capabilityInvocation","capabilityDelegation","keyAgreement"]}],"services":[{"id":"serviceId0","type":"someType","serviceEndpoint":"https://www.url.com"}]}}]}}' \
http://localhost:3000/operations

--- 1. CREATE OPERATION RESPONSE ---

{"@context":"https://w3id.org/did-resolution/v1","didDocument":{"id":"did:ion:EiCBqjANYDpKBlK9RuH7M-Aj9SLWK3s8hfhLkZ175FMwww","@context":["https://www.w3.org/ns/did/v1",{"@base":"did:ion:EiCBqjANYDpKBlK9RuH7M-Aj9SLWK3s8hfhLkZ175FMwww"}],"service":[{"id":"#serviceId0","type":"someType","serviceEndpoint":"https://www.url.com"}],"verificationMethod":[{"id":"#signingKey","controller":"","type":"EcdsaSecp256k1VerificationKey2019","publicKeyJwk":{"kty":"EC","crv":"secp256k1","x":"qCMZ35fujJut5x3V0C7Zwm6saxggPp91Wtf6iWyu0kY","y":"1MwzYwNR1RW5juCaNdhLbwhw8TTyGgJVgDhDWGBKico"}}],"authentication":["#signingKey"],"assertionMethod":["#signingKey"],"capabilityInvocation":["#signingKey"],"capabilityDelegation":["#signingKey"],"keyAgreement":["#signingKey"]},"didDocumentMetadata":{"method":{"published":false,"recoveryCommitment":"EiDVaPWhmSZ4Ytp5JfmTuKIHAYySw9ZS0dxG3vd9pxb3pw","updateCommitment":"EiBJQqYrab1Fw_Mo6SCihrVBfF4s7wGqYLVkgQvJHgfyUg"},"canonicalId":"did:ion:EiCBqjANYDpKBlK9RuH7M-Aj9SLWK3s8hfhLkZ175FMwww"}}

--- 2. CREATE RESOLVE REQUEST ---

curl http://localhost:3000/identifiers/did:ion:EiCBqjANYDpKBlK9RuH7M-Aj9SLWK3s8hfhLkZ175FMwww

--- 2. CREATE RESOLVE RESPONSE ---

{"@context":"https://w3id.org/did-resolution/v1","didDocument":{"id":"did:ion:EiCBqjANYDpKBlK9RuH7M-Aj9SLWK3s8hfhLkZ175FMwww","@context":["https://www.w3.org/ns/did/v1",{"@base":"did:ion:EiCBqjANYDpKBlK9RuH7M-Aj9SLWK3s8hfhLkZ175FMwww"}],"service":[{"id":"#serviceId0","type":"someType","serviceEndpoint":"https://www.url.com"}],"verificationMethod":[{"id":"#signingKey","controller":"","type":"EcdsaSecp256k1VerificationKey2019","publicKeyJwk":{"kty":"EC","crv":"secp256k1","x":"qCMZ35fujJut5x3V0C7Zwm6saxggPp91Wtf6iWyu0kY","y":"1MwzYwNR1RW5juCaNdhLbwhw8TTyGgJVgDhDWGBKico"}}],"authentication":["#signingKey"],"assertionMethod":["#signingKey"],"capabilityInvocation":["#signingKey"],"capabilityDelegation":["#signingKey"],"keyAgreement":["#signingKey"]},"didDocumentMetadata":{"method":{"published":true,"recoveryCommitment":"EiDVaPWhmSZ4Ytp5JfmTuKIHAYySw9ZS0dxG3vd9pxb3pw","updateCommitment":"EiBJQqYrab1Fw_Mo6SCihrVBfF4s7wGqYLVkgQvJHgfyUg"},"canonicalId":"did:ion:EiCBqjANYDpKBlK9RuH7M-Aj9SLWK3s8hfhLkZ175FMwww"}}

--- 3. UPDATE OPERATION REQUEST ---

curl --header "Content-Type: application/json" \
--request POST \
--data '{"type":"update","didSuffix":"EiDMp1jbsqH56OUYFsTfR0xQB1Sap9ndbcTyaoVew87NOw","revealValue":"EiCOlwZvr4rTyAZLUl18f3TDykZo9f9kdy_wFFVQx8iadA","delta":{"patches":[{"action":"remove-public-keys","ids":["signingKey"]}],"updateCommitment":"EiD_UnusedNextUpdateCommitmentHash_AAAAAAAAAAA"},"signedData":"eyJhbGciOiJFUzI1NksifQ.eyJ1cGRhdGVLZXkiOnsia3R5IjoiRUMiLCJjcnYiOiJzZWNwMjU2azEiLCJ4IjoiZzNsVFhLY1F6eGRzdElXNl9IOEpRcnJuMTVuNjF1Q21CZGl3NkVCZjFQcyIsInkiOiJTMkdVYldfSFRsMmJnaGhQQVFUTFpkZ0xtbzJPTGoxRkVzeURYRHduZGNnIn0sImRlbHRhSGFzaCI6IkVpQnVhUHRmNVVtVG01SHVMNHVEOGRSQl9Xak5iMEJNUmp1R3k2MHZHbzZmV2cifQ.5bLUtg4AnVIzELRBuTwavfmU7QWKeJ8zZGsFPKKEYk_j1GbU3I0RVCRxuDggRLvdfPhHzUjGHn2tu9KigyQqSQ"}' \
http://localhost:3000/operations

--- 3. UPDATE OPERATION REQUEST ---

(none)

--- 4. UPDATE RESOLVE REQUEST ---

curl http://localhost:3000/identifiers/did:ion:EiCBqjANYDpKBlK9RuH7M-Aj9SLWK3s8hfhLkZ175FMwww

--- 4. UPDATE RESOLVE REQUEST ---

{"@context":"https://w3id.org/did-resolution/v1","didDocument":{"id":"did:ion:EiCBqjANYDpKBlK9RuH7M-Aj9SLWK3s8hfhLkZ175FMwww","@context":["https://www.w3.org/ns/did/v1",{"@base":"did:ion:EiCBqjANYDpKBlK9RuH7M-Aj9SLWK3s8hfhLkZ175FMwww"}],"service":[{"id":"#serviceId0","type":"someType","serviceEndpoint":"https://www.url.com"}],"verificationMethod":[{"id":"#signingKey","controller":"","type":"EcdsaSecp256k1VerificationKey2019","publicKeyJwk":{"kty":"EC","crv":"secp256k1","x":"qCMZ35fujJut5x3V0C7Zwm6saxggPp91Wtf6iWyu0kY","y":"1MwzYwNR1RW5juCaNdhLbwhw8TTyGgJVgDhDWGBKico"}}],"authentication":["#signingKey"],"assertionMethod":["#signingKey"],"capabilityInvocation":["#signingKey"],"capabilityDelegation":["#signingKey"],"keyAgreement":["#signingKey"]},"didDocumentMetadata":{"method":{"published":true,"recoveryCommitment":"EiDVaPWhmSZ4Ytp5JfmTuKIHAYySw9ZS0dxG3vd9pxb3pw","updateCommitment":"EiBJQqYrab1Fw_Mo6SCihrVBfF4s7wGqYLVkgQvJHgfyUg"},"canonicalId":"did:ion:EiCBqjANYDpKBlK9RuH7M-Aj9SLWK3s8hfhLkZ175FMwww"}}
```

And this doesn't actually seem to work because the did isn't changed after the update operation. We just get the same content back. So i might be doing something stupid, or this isn't the same set of operations to work from. We'll try logging and looking at more tests. Maybe we can find some code that will spit out the fixtures we're looking for.

**Comment by BenjaminMoe** [comment]
I added a number on to the files, and it looks like the test is looping over a number of conditions. 

```
10_create.json  15_did.txt      20_create.json  25_did.txt      30_create.json  35_did.txt      6_create.json
10_did.txt      16_create.json  20_did.txt      26_create.json  30_did.txt      36_create.json  6_did.txt
11_create.json  16_did.txt      21_create.json  26_did.txt      31_create.json  36_did.txt      7_create.json
11_did.txt      17_create.json  21_did.txt      27_create.json  31_did.txt      3_create.json   7_deactivate.json
12_create.json  17_did.txt      22_create.json  27_did.txt      32_create.json  3_did.txt       7_did.txt
12_did.txt      18_create.json  22_did.txt      28_create.json  32_did.txt      3_update.dat    8_create.json
13_create.json  18_did.txt      23_create.json  28_did.txt      33_create.json  3_update.json   8_did.txt
13_did.txt      19_create.json  23_did.txt      29_create.json  33_did.txt      4_create.json   9_create.json
14_create.json  19_did.txt      24_create.json  29_did.txt      34_create.json  4_did.txt       9_did.txt
14_did.txt      1_create.json   24_did.txt      2_create.json   34_did.txt      5_create.json
15_create.json  1_did.txt       25_create.json  2_did.txt       35_create.json  5_did.txt
```

Would probably explain why the previous attempt didn't work. The weird thing is we only have update for 3 and deactivate for 7. Not sure why we have a loop, but only does some of the operations? Either way, if we have some operations that line up, we might as well try them. 

```
--- 1. CREATE OPERATION REQUEST ---

curl --header "Content-Type: application/json" \
--request POST \
--data '{"type":"create","suffixData":{"deltaHash":"EiCP3wvG4ppAqvjlE-jjsCOnoWuMxKAkJZgkvIIVLHMKUQ","recoveryCommitment":"EiDWGZ7CdyWt9ruaTuDsESkOQ0g_rnCeeBZJzKDYOojJDQ"},"delta":{"updateCommitment":"EiDdWych0Oko2I_TTqQ82Zj03e2_MEeHu6jQkzgfy0j9iA","patches":[{"action":"replace","document":{"publicKeys":[{"id":"signingKey","type":"EcdsaSecp256k1VerificationKey2019","publicKeyJwk":{"kty":"EC","crv":"secp256k1","x":"8owWDRBGZgS8FzppxJ-_661TUnuCBBgcmEHXmYySMDE","y":"BPHsva9o7H8GW6_DeBIcp9dECwmTWZd-IERNgHftKvY"},"purposes":["authentication","assertionMethod","capabilityInvocation","capabilityDelegation","keyAgreement"]}],"services":[{"id":"serviceId0","type":"someType","serviceEndpoint":"https://www.url.com"}]}}]}}' \
http://localhost:3000/operations

--- 1. CREATE OPERATION RESPONSE ---

{"@context":"https://w3id.org/did-resolution/v1","didDocument":{"id":"did:ion:EiBrSZ6Yf8q8N44kYVNdrobFKlR-DDXLqZr5esLUlHs2Ww","@context":["https://www.w3.org/ns/did/v1",{"@base":"did:ion:EiBrSZ6Yf8q8N44kYVNdrobFKlR-DDXLqZr5esLUlHs2Ww"}],"service":[{"id":"#serviceId0","type":"someType","serviceEndpoint":"https://www.url.com"}],"verificationMethod":[{"id":"#signingKey","controller":"","type":"EcdsaSecp256k1VerificationKey2019","publicKeyJwk":{"kty":"EC","crv":"secp256k1","x":"8owWDRBGZgS8FzppxJ-_661TUnuCBBgcmEHXmYySMDE","y":"BPHsva9o7H8GW6_DeBIcp9dECwmTWZd-IERNgHftKvY"}}],"authentication":["#signingKey"],"assertionMethod":["#signingKey"],"capabilityInvocation":["#signingKey"],"capabilityDelegation":["#signingKey"],"keyAgreement":["#signingKey"]},"didDocumentMetadata":{"method":{"published":false,"recoveryCommitment":"EiDWGZ7CdyWt9ruaTuDsESkOQ0g_rnCeeBZJzKDYOojJDQ","updateCommitment":"EiDdWych0Oko2I_TTqQ82Zj03e2_MEeHu6jQkzgfy0j9iA"},"canonicalId":"did:ion:EiBrSZ6Yf8q8N44kYVNdrobFKlR-DDXLqZr5esLUlHs2Ww"}}

--- 1. CREATE RESOLVE REQUEST ---

curl http://localhost:3000/identifiers/did:ion:EiBrSZ6Yf8q8N44kYVNdrobFKlR-DDXLqZr5esLUlHs2Ww

--- 1. CREATE RESOLVE RESPONSE ---

{"@context":"https://w3id.org/did-resolution/v1","didDocument":{"id":"did:ion:EiBrSZ6Yf8q8N44kYVNdrobFKlR-DDXLqZr5esLUlHs2Ww","@context":["https://www.w3.org/ns/did/v1",{"@base":"did:ion:EiBrSZ6Yf8q8N44kYVNdrobFKlR-DDXLqZr5esLUlHs2Ww"}],"service":[{"id":"#serviceId0","type":"someType","serviceEndpoint":"https://www.url.com"}],"verificationMethod":[{"id":"#signingKey","controller":"","type":"EcdsaSecp256k1VerificationKey2019","publicKeyJwk":{"kty":"EC","crv":"secp256k1","x":"8owWDRBGZgS8FzppxJ-_661TUnuCBBgcmEHXmYySMDE","y":"BPHsva9o7H8GW6_DeBIcp9dECwmTWZd-IERNgHftKvY"}}],"authentication":["#signingKey"],"assertionMethod":["#signingKey"],"capabilityInvocation":["#signingKey"],"capabilityDelegation":["#signingKey"],"keyAgreement":["#signingKey"]},"didDocumentMetadata":{"method":{"published":true,"recoveryCommitment":"EiDWGZ7CdyWt9ruaTuDsESkOQ0g_rnCeeBZJzKDYOojJDQ","updateCommitment":"EiDdWych0Oko2I_TTqQ82Zj03e2_MEeHu6jQkzgfy0j9iA"},"canonicalId":"did:ion:EiBrSZ6Yf8q8N44kYVNdrobFKlR-DDXLqZr5esLUlHs2Ww"}}

--- 2. UPDATE OPERATION REQUEST ---

(skip)

--- 2. UPDATE OPERATION REQUEST ---

(skip)

--- 2. UPDATE RESOLVE REQUEST ---

(skip)

--- 2. UPDATE RESOLVE REQUEST ---

(skip)

--- 3. DEACTIVATE OPERATION REQUEST ---

curl --header "Content-Type: application/json" \
--request POST \
--data '{"type":"deactivate","didSuffix":"EiBrSZ6Yf8q8N44kYVNdrobFKlR-DDXLqZr5esLUlHs2Ww","revealValue":"EiB-G0e6YbPNmj-e94MXTIPvUMfQaTcBmqO0XBDArQe5bQ","signedData":"eyJhbGciOiJFUzI1NksifQ.eyJkaWRTdWZmaXgiOiJFaUJyU1o2WWY4cThONDRrWVZOZHJvYkZLbFItRERYTHFacjVlc0xVbEhzMld3IiwicmVjb3ZlcnlLZXkiOnsia3R5IjoiRUMiLCJjcnYiOiJzZWNwMjU2azEiLCJ4IjoiaFR6TnRtaGpLNVdZYmNMeFFhM05qQldSZnBkWG5PWlU0ZHg5VG10cU1lOCIsInkiOiJnWmxfRUpYR3dmbkNDUmJkSDd1Vjg4YllzZ3plUExfRGY2c0o4Y1JNWlVrIn19.9uhncNwbhU6Lg0e2FPeTdup4wrHs3PK6y-U0T27dIRLamFHmfwqtdSc7ba8GIwnyVpNhIhXS4Pwi9gA3PubLmQ"}' \
http://localhost:3000/operations

--- 3. DEACTIVATE OPERATION RESPONSE ---

( empty string)

--- 3. DEACTIVATE RESOLVE REQUEST ---

curl http://localhost:3000/identifiers/did:ion:EiBrSZ6Yf8q8N44kYVNdrobFKlR-DDXLqZr5esLUlHs2Ww

--- 3. DEACTIVATE RESOLVE RESPONSE ---

{"@context":"https://w3id.org/did-resolution/v1","didDocument":{"id":"did:ion:EiBrSZ6Yf8q8N44kYVNdrobFKlR-DDXLqZr5esLUlHs2Ww","@context":["https://www.w3.org/ns/did/v1",{"@base":"did:ion:EiBrSZ6Yf8q8N44kYVNdrobFKlR-DDXLqZr5esLUlHs2Ww"}]},"didDocumentMetadata":{"method":{"published":true},"canonicalId":"did:ion:EiBrSZ6Yf8q8N44kYVNdrobFKlR-DDXLqZr5esLUlHs2Ww"}}
```

**Comment by BenjaminMoe** [comment]
Managed to re-write Sidetree's tests to spit out test vectors that I can use. I'm not sure how to take advantage of the recover operation, so I will split this into two different vectors. 

First we have create and recover with one did. And then we do create, update, and deactivate on a second did. I think it's easier to split it out into multiple did's. But I think for illustrative purposes I think it would be better to show the life-cycle of one did being changed over multiple requests, and then showing the differences between the resolved document after each modification. 

For now we'll do the following tests. Once we can look at what's going, maybe we can come back and refine.

**Create + Recover**

```
curl --header "Content-Type: application/json" --request POST --data '{"type":"create","suffixData":{"deltaHash":"EiCP8MJ9oX2jmTxVi6xa1WoGmzkg8HaxmWWiR6R34cUmvw","recoveryCommitment":"EiCFei9R_74JeKbxGIZPI4XXwbb0eDpBeweA9IpymBEOFA"},"delta":{"updateCommitment":"EiDDJ-s9CPjkh6yaH5apLIKZ1G87K0phukB3Fofy2ujeAg","patches":[{"action":"replace","document":{"publicKeys":[{"id":"signingKey","type":"EcdsaSecp256k1VerificationKey2019","publicKeyJwk":{"kty":"EC","crv":"secp256k1","x":"8a7JVJUDcR_mS6gyTAgdvGFZkhO8plwWfId3xqHa7xA","y":"xIxXstl9XR-hXXBkrhzxrFhJRvab2MLhQDus92S8G2o"},"purposes":["authentication","assertionMethod","capabilityInvocation","capabilityDelegation","keyAgreement"]}],"services":[{"id":"serviceId123","type":"someType","serviceEndpoint":"https://www.url.com"}]}}]}}' http://localhost:3000/operations

curl http://localhost:3000/identifiers/did:ion:EiB_4F3m_qz5tBdRmC7tcMOQJxvKSyICzQ4Uxt8cGTN5Vg

curl --header "Content-Type: application/json" --request POST --data '{"type":"recover","didSuffix":"EiB_4F3m_qz5tBdRmC7tcMOQJxvKSyICzQ4Uxt8cGTN5Vg","revealValue":"EiBDFxzWmxgVG9SH-PY-9Yz73-6mnI8egnypTx1fjlKMKw","signedData":"eyJhbGciOiJFUzI1NksifQ.eyJkZWx0YUhhc2giOiJFaURaeXJBQk13dGZ1YmNGSXlZelhkb09wNXdObzZCNW82MGxvaUg1Qkh3VldRIiwicmVjb3ZlcnlLZXkiOnsia3R5IjoiRUMiLCJjcnYiOiJzZWNwMjU2azEiLCJ4IjoiODZzeDZ5dVdZWjVMRFp1WFd4WF9FdEtrbFN1a21jSDdQZUIzNFNrWUVjZyIsInkiOiJzVlR6VGhVejNDRk82N2doWHVIQXV6Q2ZCVWdKa0V3WkZrbzZQM0ZzNnIwIn0sInJlY292ZXJ5Q29tbWl0bWVudCI6IkVpREFUNGxlYm14S3FTOXFyT1ROZ0lOakJ1aHY1VUJWS1h3Y0NQQ0hiellNX1EifQ.w9jDo4hrTVxbA3oA7QH6YOiTSM5y1f697Dj7m4DPg3ShbhjK3KwXmrHEu5lpFXcxAFB47hW0G1rzm7PpNm9bwQ","delta":{"patches":[{"action":"replace","document":{"publicKeys":[]}}],"updateCommitment":"EiDDJ-s9CPjkh6yaH5apLIKZ1G87K0phukB3Fofy2ujeAg"}}' http://localhost:3000/operations

curl http://localhost:3000/identifiers/did:ion:EiB_4F3m_qz5tBdRmC7tcMOQJxvKSyICzQ4Uxt8cGTN5Vg
```

**Create + Update + Deactivate**

```
curl --header "Content-Type: application/json" --request POST --data '{"type":"create","suffixData":{"deltaHash":"EiB5bpeOg4EMw3rYAZ37wmdqrHAoZVf45-70EeeFBLIDxA","recoveryCommitment":"EiCYJN3wDMCQc5kJo_ZR6nNiLEukVZEd3qgTrSHQZIy-NA"},"delta":{"updateCommitment":"EiDJa1d1800h2jcvLOJ5eoga5PrIA9WAwxrKGvUYXJwTeQ","patches":[{"action":"replace","document":{"publicKeys":[{"id":"signingKey","type":"EcdsaSecp256k1VerificationKey2019","publicKeyJwk":{"kty":"EC","crv":"secp256k1","x":"naoGdqBTAvOAVaXjRJb_MW2BPw86iGWLs4i9ylN0dbE","y":"dOfZc0yVkTm70h_ixQOu-B_T29dzxGTILf1-xoqYeao"},"purposes":["authentication","assertionMethod","capabilityInvocation","capabilityDelegation","keyAgreement"]}],"services":[{"id":"serviceId123","type":"someType","serviceEndpoint":"https://www.url.com"}]}}]}}' http://localhost:3000/operations

curl http://localhost:3000/identifiers/did:ion:EiBuuicWVxOcbhCW0N9YSRJwB7auqbzhMhKg1qXRTR30_A

curl --header "Content-Type: application/json" --request POST --data '{"type":"recover","didSuffix":"EiBuuicWVxOcbhCW0N9YSRJwB7auqbzhMhKg1qXRTR30_A","revealValue":"EiCk-d_6aijSJVJ9K00qlfprLUew_TUZqZ4b8dtl_5mpww","signedData":"eyJhbGciOiJFUzI1NksifQ.eyJkZWx0YUhhc2giOiJFaUJueUFRT1NMbDhxc2E2Q3lWaEt4Q2ZFbzZ1VEViOHRYRm1aY0l1eHYwS3lnIiwicmVjb3ZlcnlLZXkiOnsia3R5IjoiRUMiLCJjcnYiOiJzZWNwMjU2azEiLCJ4IjoiLUhWWFJRNVNGTnRoWFk2Mkxya3N2Z2dqdkVlaEF1Sll3bTVkS0ZZSzJ5ZyIsInkiOiJqQVVqYmo5N3I2dDNTY0pvVW1DTjRwejRpdXVpdGVrMEtKSlFaMndHU1g4In0sInJlY292ZXJ5Q29tbWl0bWVudCI6IkVpREJXZ3VlblBPSm1JZ2U3Zm41azl6S1R0bHRPWEZxYVRvenVNQUpZM21tS1EifQ.iz6mBwkAS437-id3Ne12eHychkcGt7mtICux02DbNUgiPGPimWjhPRtJYSX2GCeabxb1U9az5OhnwtUiTBvkeg","delta":{"patches":[{"action":"replace","document":{"publicKeys":[]}}],"updateCommitment":"EiDJa1d1800h2jcvLOJ5eoga5PrIA9WAwxrKGvUYXJwTeQ"}}' http://localhost:3000/operations

curl http://localhost:3000/identifiers/did:ion:EiBuuicWVxOcbhCW0N9YSRJwB7auqbzhMhKg1qXRTR30_A

curl --header "Content-Type: application/json" --request POST --data '{"type":"update","didSuffix":"EiBuuicWVxOcbhCW0N9YSRJwB7auqbzhMhKg1qXRTR30_A","revealValue":"EiD0FtXueh5RDV_DlLcOuxjPnT-pheGPfhvaYUivLpGmZA","delta":{"patches":[{"action":"add-services","services":[{"id":"someId","type":"someType","serviceEndpoint":"someEndpoint"}]}],"updateCommitment":"EiDJa1d1800h2jcvLOJ5eoga5PrIA9WAwxrKGvUYXJwTeQ"},"signedData":"eyJhbGciOiJFUzI1NksifQ.eyJ1cGRhdGVLZXkiOnsia3R5IjoiRUMiLCJjcnYiOiJzZWNwMjU2azEiLCJ4IjoiMTdOVnAwX3pwLUJON3FkeTJhbkNqcDk1TS1sVF9pZ2xpTENEZ1hvS2F6YyIsInkiOiJ4TzJPQlZSOGxFTW94N1hvYzVYU1dYSC1yUm5jbHk5b2NvTVBUVkhVZmtzIn0sImRlbHRhSGFzaCI6IkVpQ2VkUlZYWGRaU0VMSmRqNzhJclVwaFVJYkVSWFA1UWlrSTN1ZEVvSmFRcEEifQ.-oeeFd4XrAf1L9pt0V_MjXIEubqAEHKPGA1s3JnrdWLHcG3uXF2wZSI_xoDMTlRuwHkJjt-tt918Ce9OXwi4PQ"}' http://localhost:3000/operations

curl http://localhost:3000/identifiers/did:ion:EiBuuicWVxOcbhCW0N9YSRJwB7auqbzhMhKg1qXRTR30_A

curl --header "Content-Type: application/json" --request POST --data '{"type":"deactivate","didSuffix":"EiBuuicWVxOcbhCW0N9YSRJwB7auqbzhMhKg1qXRTR30_A","revealValue":"EiCk-d_6aijSJVJ9K00qlfprLUew_TUZqZ4b8dtl_5mpww","signedData":"eyJhbGciOiJFUzI1NksifQ.eyJkaWRTdWZmaXgiOiJFaUJ1dWljV1Z4T2NiaENXME45WVNSSndCN2F1cWJ6aE1oS2cxcVhSVFIzMF9BIiwicmVjb3ZlcnlLZXkiOnsia3R5IjoiRUMiLCJjcnYiOiJzZWNwMjU2azEiLCJ4IjoiLUhWWFJRNVNGTnRoWFk2Mkxya3N2Z2dqdkVlaEF1Sll3bTVkS0ZZSzJ5ZyIsInkiOiJqQVVqYmo5N3I2dDNTY0pvVW1DTjRwejRpdXVpdGVrMEtKSlFaMndHU1g4In19.L9fl_GHr5jseHUckE0dx4ib-YkFiFBx5YgdFJ8_pcNa71JPTbGT2T4_WY7HUsQqBe_F-yzoDd_FozspFC2PqKw"}' http://localhost:3000/operations

curl http://localhost:3000/identifiers/did:ion:EiBuuicWVxOcbhCW0N9YSRJwB7auqbzhMhKg1qXRTR30_A
```

**Review by OR13 — APPROVED** [review]

**Pull request merged**
