### PR TITLE
Add support for eth private key

### LINKED ISSUE #374: Add support for providing a private key instead of mnemonic to run an element node
I'm following instructions [here](https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method-element/docs/docker-element-ropsten-install.md) and at some point the docs ask to provide a mnemonic. It's a bit inconvenient because:
- Don't want to provide my metamask mnemonic which has mainnet ETH on another address
- It's inconvenient to create a separate mnemonic because metamask only supports having one mnemonic, so would have to manage it some other way.

Instead, would it be possible to use Element using an exported private key? Would be easier because then people could create a separate address on metamask for Element, and export the key for running the node, while still maintaining separation with other addresses.

### PR DESCRIPTION
**Pull request by gjgd**
fixes #374 

Add support for ETHEREUM_PRIVATE_KEY in element config.

Change is backwards compatible: ETHEREUM_PRIVATE_KEY is ignored if ETHEREUM_MNEMONIC is passed

### CODE REVIEW

**Comment by Bleujj1** [comment]
You will need to synchronize your wallet first and then you debug

**Comment by gjgd** [comment]
@Bleujj1 Sounds good, tell me how I can synchronize my wallet

**Comment by Bleujj1** [comment]
I’m going to send you a secure ellipal link. You will follow the link till
you get to synchronize and then you will click on it and you reboot your
device

**Review by BenjaminMoe — APPROVED** [review]
I really like this change. For allowing payments from a specific account inside of Metamask and seprating funds that way as opposed to providing the seed.

**Comment by Bleujj1** [comment]
Okay

**Pull request merged**
