### PR TITLE
Fix dashboard build

### PR DESCRIPTION
**Pull request by OR13**
This PR fixes the build for the dashboard package.

### CODE REVIEW

**Review by gjgd — COMMENTED** [review]
I'm getting an error when running `npm run build`.

Anything else I should do?

```
➜ npm run build

> @sidetree/dashboard@0.1.0 build /Users/guillaume/workspace/sidetree.js/packages/dashboard
> next build

info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

Failed to compile.

./core/DashboardWallet.ts:9:20
Type error: Namespace '"/Users/guillaume/workspace/sidetree.js/packages/wallet/dist/index"' has no exported member 'pluginFactory'.

   7 | export interface DashboardWallet
   8 |   extends UniversalWallet.Wallet,
>  9 |     SidetreeWallet.pluginFactory.SidetreePlugin {}
     |                    ^
  10 |
  11 | export const dashboardWalletFactory: Factory.Sync.Factory<DashboardWallet> = Factory.Sync.makeFactory<
  12 |   DashboardWallet
info  - Checking validity of types .npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sidetree/dashboard@0.1.0 build: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @sidetree/dashboard@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by OR13** [comment]
@gjgd not sure, you can try `npx jest --clearCache`... 

build appears to be passing in CI: https://github.com/transmute-industries/sidetree.js/pull/275/files#diff-7823be634d672d67fd854b2a4a9d5845abe70aa056608975559746b07dd16db1R7

**Comment by gjgd** [comment]
@OR13 I don't think `npm run build` is ran in CI: https://github.com/transmute-industries/sidetree.js/blob/main/.github/workflows/ci.yml#L36

**Comment by OR13** [comment]
@gjgd I will need to run it again locally... maybe I forgot to lerna link.

**Comment by OR13** [comment]
I was able to reproduce, working on a fix.

**Comment by OR13** [comment]
@ipbyrne @BenjaminMoe @acarnagey  beware the odd web pack behavior:

```
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'events' in '.../sidetree.js/packages/crypto/node_modules/hash-base/node_modules/readable-stream/lib'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "events": require.resolve("events/") }'
	- install 'events'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "events": false }
```

Added `events` as a dev dependency to fix this, but really its probably not the correct way to think about this issue...

**Review by gjgd — APPROVED** [review]

**Comment by gjgd** [comment]
At some point, consider adding a step to build this package in CI @OR13

**Comment by OR13** [comment]
I think prepare does that: https://github.com/transmute-industries/sidetree.js/pull/275/files#diff-7823be634d672d67fd854b2a4a9d5845abe70aa056608975559746b07dd16db1R12


but yes, eventually I want to build and publish images on merge to main from this package.

**Pull request merged**
